name: loop secret

on:
  push:
    branches:
      - main

jobs: 
    do:
        runs-on: ubuntu-latest
        steps:
            - run: echo "foooobar"
            - run: echo "${{ secrets.CLIENTS }}"
            - uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: python shiz
              uses: jannekem/run-python-script-action@v1
              with:
                script: |
                  import json
                  print("theoretically loop through each one for deployment, but need to make these referencable from deployment? or somehow remake deployment all in python")
                  for item in json.loads("""${{secrets.CLIENTS}}"""):
                    print(item)