name: loop secret

on:
  push:
    branches:
      - main

jobs: 
    do:
        runs-on: ubuntu-latest
        steps:
            - run: echo "foooobar"
            - run: echo "${{ secrets.CLIENTS }}"
            - run: |
                for item in ${{ secrets.CLIENTS }}
                do
                    echo item
                done